services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: gojs-angular-basic:latest
    container_name: linkedin-email-extractor
    ports:
      - "8080:80"
    restart: unless-stopped
